config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get '/new_entry', to: 'journals#new'
  post '/new_entry', to: 'journals#create'
  get 'my_entries', to: 'journals#index'

  get '/my_dashboard', to: 'dashboards#show'

  get '/my_calendar', to: 'meetings#index'
  get '/new_meeting', to: 'meetings#new'
  post '/new_meeting', to: 'meetings#create'

  get '/my_photos', to: 'photos#index'
  get '/new_photo', to: 'photos#new'
  post '/new_photo', to: 'photos#create'

  get '/tag_search', to: 'tags#search'

  resources :journals, only: [:show, :edit, :update, :destroy] do
    resources :tags, module: :journals
  end

  resources :photos, except: [:index, :new, :create] do
    resources :tags, module: :photos
  end

  resources :agendas do
    resources :tags, module: :agendas
  end

  resource :dashboard, only: [:new, :create, :destroy]
  resource :meetings, only: [:show]
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user

  validates :title, :description, presence: true
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :find_meeting, only: [:show]

  def index
    @meetings = current_user.meetings
  end

  def new
    @meeting = current_user.meetings.build
  end

  def create
    @meeting = current_user.meetings.build(meeting_params)

    if @meeting.save
      flash[:notice] = "Event created!"
      redirect_to my_calendar_path
    else
      flash[:notice] = "Event not saved"
      redner :new
    end
  end

  def show
  end

  def destroy
    @meeting.destroy
    redirect_to my_calendar_path
  end

  private

   def meeting_params
     params.require(:meeting).permit(:title, :start_date, :description)
   end

   def find_meeting
     @meeting = Meeting.find(params[:format])
   end

end

app/views/meetings/index.html.erb
<%= month_calendar(attribute: :start_date, events: @meetings) do |date, meetings| %>
  <%= date %>
  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.title, meetings_path(meeting) %>
    </div>
  <% end %>
<% end %>

<%= link_to "Add a New Calendar Event", new_meeting_path %>

app/views/meetings/new.html.erb
<h2 class="ui centered header">New Calendar Event</h2>

<div class="ui container">
  <%= simple_form_for(@meeting, url: new_meeting_url, html: { class: "ui form" }) do |f| %>
    <div class="field">
      <%= f.input :title, placeholder: "Event Title" %>
    </div>
    <div class="field">
      <%= f.input :start_date, as: :date %>
    </div>
    <div class="field">
      <%= f.input :description %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Create Event", class: "positive ui button" %>
      <%= link_to "Cancel", my_calendar_path %>
    </div>
  <% end %>
</div>

app/views/meetings/show.html.erb
<%= render 'shared/show', item: @meeting %>