config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get '/new_entry', to: 'journals#new'
  post '/new_entry', to: 'journals#create'
  get 'my_entries', to: 'journals#index'

  get '/my_dashboard', to: 'dashboards#show'

  get '/my_calendar', to: 'meetings#index'
  get '/new_meeting', to: 'meetings#new'
  post '/new_meeting', to: 'meetings#create'

  get '/my_photos', to: 'photos#index'
  get '/new_photo', to: 'photos#new'
  post '/new_photo', to: 'photos#create'

  get '/tag_search', to: 'tags#search'

  resources :journals, only: [:show, :edit, :update, :destroy] do
    resources :tags, module: :journals
  end

  resources :photos, except: [:index, :new, :create] do
    resources :tags, module: :photos
  end

  resources :agendas do
    resources :tags, module: :agendas
  end

  resource :dashboard, only: [:new, :create, :destroy]
  resource :meetings, only: [:show]
end

app/views/shared/_footer.html.erb
<div class="ui small menu footer">
  <%= link_to "About", about_path, class: "active item left floated" %>
  <div class="item right menu">
    Made by: Drew Hund - 2020
  </div>
</div>

app/views/shared/_index.html.erb
<div class="ui grid">
  <%= items.each do |item| %>
    <div class="ui four wide column">
      <div class="ui card">
        <div class="content">
          <div class="centered header">
            <%if item.is_a?(Journal) %>
              <%= link_to item.title, journal_path(item) %>
            <% elsif item.is_a?(Photo) %>
              <%= link_to item.title, photo_path(item) %>
            <% else %>
              <%= link_to item.title, agenda_path(item) %>
            <% end %>
          </div>
        </div>
        <div class="content blurb"><%= (item.is_a?(Photo) ? image_tag(item.show_image) : item.body) %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<div class="ui huge menu">
  <%= link_to "Time Capsule", root_path, class: "active item" %>
  <%= render 'shared/search' %>
  <div class="right menu">
    <% if !user_signed_in? %>
      <%= link_to "Sign In", new_user_session_path, class: "item right floated" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "item right floated" %>
    <% else %>
      <div class="ui right item">
        <%= link_to "My Dashboard", my_dashboard_path %>
      </div>
      <div class="ui dropdown right item">
        New Project
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item"><%= link_to "Journal Entry", new_entry_path %></div>
          <div class="item"><%= link_to "Photo", new_photo_path %></div>
          <div class="item"><%= link_to "To-Do", new_agenda_path %></div>
          <div class="item"><%= link_to "View my Calendar", my_calendar_path %></div>
        </div>
      </div>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "item right floated" %>
    <% end %>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for(:tags, url: tag_search_path, method: :GET, html: { class: "search-form"}) do |f| %>
  <div class="ui category search">
    <div class="ui icon input search-input">
      <%= f.input :tag, placeholder: "Search entries by tag...", html: { class: "prompt" } %>
      <i class="search icon"></i>
    </div>
  </div>
<% end %>

app/views/shared/_show.html.erb
<div class="ui segment">
  <p class="item-title"><strong><%= item.title %></strong></p>
  <hr>
  <p>
    <% if item.is_a?(Journal) %>
      <%= item.body %>
    <% elsif item.is_a?(Agenda) %>
      <%= item.body %>
    <% elsif item.is_a?(Meeting) %>
      <%= item.description %>
    <% else %>
      <%= image_tag item.image %>
      <p><%= item.summary %></p>
    <% end %>
  </p>
  <% unless item.is_a?(Meeting) %>
    <p>
      <small>Tags: <%= raw item.tags.map(&:name).join(", ") %></small>
    </p>
    <%= render 'tags/form', taggable: item %>
  <% end %>
  <%= link_to "Delete Entry", (item.is_a?(Journal) ? journal_path(item) :
                         item.is_a?(Photo) ? photo_path(item) :
                         item.is_a?(Meeting) ? meetings_path(item) : agendas_path(item)), method: :delete,
                         data: { confirm: "Are you sure?" }, class: "ui negative button delete-entry" %>
</div>

app/views/shared/_tags_form.html.erb
<%= simple_form_for([taggable, Tag.new]) do |f| %>
  <div class="field">
    <%= f.input :tags, collection: Journal::TAGS, input_html: { multipart: true, multiple: true } %>
  </div>
<% end %>