config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get '/new_entry', to: 'journals#new'
  post '/new_entry', to: 'journals#create'
  get 'my_entries', to: 'journals#index'

  get '/my_dashboard', to: 'dashboards#show'

  get '/my_calendar', to: 'meetings#index'
  get '/new_meeting', to: 'meetings#new'
  post '/new_meeting', to: 'meetings#create'

  get '/my_photos', to: 'photos#index'
  get '/new_photo', to: 'photos#new'
  post '/new_photo', to: 'photos#create'

  get '/tag_search', to: 'tags#search'

  resources :journals, only: [:show, :edit, :update, :destroy] do
    resources :tags, module: :journals
  end

  resources :photos, except: [:index, :new, :create] do
    resources :tags, module: :photos
  end

  resources :agendas do
    resources :tags, module: :agendas
  end

  resource :dashboard, only: [:new, :create, :destroy]
  resource :meetings, only: [:show]
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def new
    @dashboard = current_user.dashboard.build
  end

  def create
    @dashboard = current_user.dashboard.build(dashboard_params)
    if @dashboard.save
      redirect_to dashboard_path
    end
  end

  def show
    @journals = current_user.journals.all
  end

  def show
    @dashboard = current_user.dashboard
  end

  private

    def dashboard_params
      params.require(:dashboard).permit(:user_id)
    end

end

app/views/dashboards/show.html.erb
<h2 class="ui centered header">My Dashboard</h2>

<div class="ui grid">
  <div class="ui four wide column">
    <!-- loop through all a users topicables and generate a card for each (current_user.topicables.each do) -->
    <div class="ui card">
      <div class="content">
        <div class="centered header"><%= link_to "My Journals", my_entries_path, entries: @journals %></div>
      </div>
      <div class="content blurb">
        See what you've written, you star author, you!
        Our thoughts are valuable and deserve to be written, if only for your own eyes.
        Get your ideas out there adn see them become manifest in the real world! And then come back to find them here,
        so they don't get lost out in the big, wide universe.
      </div>
    </div>
  </div>
  <div class="ui four wide column">
    <!-- loop through all a users topicables and generate a card for each (current_user.topicables.each do) -->
    <div class="ui card">
      <div class="content">
        <div class="centered header"><%= link_to "My Photos", my_photos_path %></div>
      </div>
      <div class="content blurb">
        What photos have you found recently? Did you take any cool photos of your own?
        Come see your blossoming photo gallery! Who knows, maybe you'll develop a talent for scrapbooking,
        or a knack for amateur photography! Either way, your creations or photo collection should live somewhere.
        Probably not here in the long run, but at least for now.
      </div>
    </div>
  </div>
  <div class="ui four wide column">
    <!-- loop through all a users topicables and generate a card for each (current_user.topicables.each do) -->
    <div class="ui card">
      <div class="content">
        <div class="centered header"><%= link_to "My To-Dos", agendas_path %></div>
      </div>
      <div class="content blurb">
        Who has time to find a new piece of paper or spin up a phone app when you're out and about, just dump your
        to-dos here instead! That is the point of this site, after all - to have one location to keep everything you're up to these days.
        And people are up to a lot these days! We really should take some time for ourselves in between...
      </div>
    </div>
  </div>
  <div class="ui four wide column">
    <!-- loop through all a users topicables and generate a card for each (current_user.topicables.each do) -->
    <div class="ui card">
      <div class="content">
        <div class="centered header"><%= link_to "My Calendar", my_calendar_path %></div>
      </div>
      <div class="content blurb">
        Got a hot date? An oil change appointment? Other things that are important but maybe not important to put in your google calendar?
        Put them here! Then you can open up your calendar and see what you got goin on, you ray of sunshine.
      </div>
    </div>
  </div>
</div>