config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get '/new_entry', to: 'journals#new'
  post '/new_entry', to: 'journals#create'
  get 'my_entries', to: 'journals#index'

  get '/my_dashboard', to: 'dashboards#show'

  get '/my_calendar', to: 'meetings#index'
  get '/new_meeting', to: 'meetings#new'
  post '/new_meeting', to: 'meetings#create'

  get '/my_photos', to: 'photos#index'
  get '/new_photo', to: 'photos#new'
  post '/new_photo', to: 'photos#create'

  get '/tag_search', to: 'tags#search'

  resources :journals, only: [:show, :edit, :update, :destroy] do
    resources :tags, module: :journals
  end

  resources :photos, except: [:index, :new, :create] do
    resources :tags, module: :photos
  end

  resources :agendas do
    resources :tags, module: :agendas
  end

  resource :dashboard, only: [:new, :create, :destroy]
  resource :meetings, only: [:show]
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :tags, as: :taggable
  has_one_attached :image

  validates :image, presence: true
  validates :image, content_type: { in: %w[image/jpeg, image/jpg, image/gif, image/png],
                                    message: "Must be a valid image type" },
                                    size: { less_than: 10.megabytes, message: "Must be 10mb or smaller" }
  validates :summary, presence: true
  validates :summary, length: { maximum: 150 }

  def show_image
    image.variant(resize_to_limit: [200, 200])
  end

end

app/controllers/photos/tags_controller.rb
class Photos::TagsController < TagsController
  before_action :set_taggable

  private

    def set_taggable
      @taggable = Photo.find(params[:photo_id])
    end
    
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, except: [:index, :new, :create]

  def index
    @photos = current_user.photos
  end

  def new
    @photo = current_user.photos.build
  end

  def create
    @photo = current_user.photos.build(photo_params)
    @photo.image.attach(params[:photo][:image])

    if @photo.save
      flash[:notice] = "Add tags to make this entry searchable!"
      redirect_to @photo
    else
      flash[:notice] = "Something went wrong, please try again"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @photo.update(photo_params)
    tags.each { |tag| @photo.tags.create(name: tag) }
  end

  def destroy
    @photo.destroy
    flash[:notice] = "Photo successfulyl removed"
    redirect_to my_photos_path
  end

  private

    def find_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      permitted_params.except(:tags)
    end

    def permitted_params
      params.require(:photo).permit(:title, :summary, :image, tags: [])
    end

    def tags
      permitted_params.slice(:tags)
    end

end

app/views/photos/edit.html.erb
<h2 class="ui centered header">Edit Photo Entry</h2>

<div class="ui container">
  <%= simple_form_for(@photo, local: true, html: { class: "ui form" }) do |f| %>
    <div class="field">
      <%= image_tag @photo.show_image %>
    </div>
    <div class="field">
      <%= f.input :title, required: true %>
    </div>
    <div class="field">
      <%= f.label :summary %>
      <%= f.input :summary, required: true %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Update Photo", class: "positive ui button" %>
      <%= link_to "Cancel", root_path %>
    </div>
  <% end %>
</div>

app/views/photos/index.html.erb
<%= render 'shared/index', items: @photos %>

app/views/photos/new.html.erb
<h2 class="ui centered header">Upload a New Photo</h2>

<div class="ui container">
  <%= simple_form_for(@photo, url: new_photo_url, html: { class: "ui form" }) do |f| %>
    <%= render 'shared/messages' %>
    <div class="field">
      <%= f.input :title, required: true %>
    </div>
    <div class="field">
      <%= f.input :image, as: :file, required: true %>
    </div>
    <div class="field">
      <%= f.input :summary, required: true %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Upload Photo", class: "positive ui button" %>
      <%= link_to "Cancel", my_dashboard_path %>
    </div>
  <% end %>
</div>

app/views/photos/show.html.erb
<%= render 'shared/show', item: @photo %>